### ISSUE TITLE
Name spacing issue with Berkshelf, Chef Supermarket and cookbook metadata.

### ISSUE THREAD

**Issue by Joseph-R** [spheromak/sysctl-cookbook#14]
There appears to be an issue with the cookbook name spacing that is causing problems with Berkshelf.

Error:

```
Fetching 'sysctl-cookbook' from git@github.com:spheromak/sysctl-cookbook.git (at master)
In your Berksfile, you have:

  cookbook 'sysctl-cookbook'

But that cookbook is actually named 'sysctl'

This can cause potentially unwanted side-effects in the future.

NOTE: If you do not explicitly set the 'name' attribute in the metadata, the name of the directory will be used instead. This is often a cause of confusion for dependency solving.
```

Where my Berksfile looks like this:

```
source "https://supermarket.chef.io"


cookbook 'ambari', git: "git@github.com:jp/ambari.git"
cookbook 'O2O-base', git: "git@github.com:korrelate/O2O-base.git"
cookbook 'sysctl-cookbook', git: "git@github.com:spheromak/sysctl-cookbook.git"

# Scan cookbook metadata file for dependencies to resolve.
metadata
```

As you can see, Berkshelf searches the Chef supermarket first, for cookbooks named `sysctl`.  And since [there already is one](https://github.com/svanzoest-cookbooks/sysctl/), setting `cookbook 'sysctl-cookbook'` isn't an option.  (It would pull the other cookbook.)

So I have specified the git repo for this cookbook.  However, since the name you have configured in [your cookbook metadata](https://github.com/spheromak/sysctl-cookbook/blob/master/metadata.rb) doesn't match the github project name `sysctl-cookbook`, I'm getting errors.

I have resolved this by changing `cookbook 'sysctl-cookbook', git: "git@github.com:spheromak/sysctl-cookbook.git"` to `cookbook 'sysctl', git: "git@github.com:spheromak/sysctl-cookbook.git"`, but that override is pretty sloppy and, imo, leads to confusing code somebody else may trip over later.

The ideal solution would be to change the cookbook name in the metadata to match the github project name.  Are you guys open to that?

Regards,
Joe Reid

**Comment by spheromak** [comment]
use `cookbook 'sysctl'`  in your berksfile. That is the way to deal with this, and is quite common.

The point is to be detached from the git project name. As this isn't in a 'cookbooks' repository it would collide in repository where say I had a code projected named `foo` and potentially a cookbook for that code named `foo-cookbook`. In chef I want that named `foo` not `foo-cookbook` thus the reason there is that name field and a source field that don't have to line up.
