### ISSUE TITLE
many sysctl cookbook

### ISSUE THREAD

**Issue by guilhem** [spheromak/sysctl-cookbook#3]
Hi,

We seems to have a "problem" with sysctl cookbook.

We have the "original": https://github.com/Fewbytes/sysctl-cookbook

Mine: https://github.com/Youscribe/sysctl-cookbook
a fork from mine: https://github.com/rcbops-cookbooks/sysctl (I merged it)

and yours.

I will do the same issue in all this cookbook.
I will be happy to discuss with everyone not to do the same-things 1000x.

**Comment by spheromak** [comment]
I am happy to talk about it. I created this when there was only the "original" out in public.  If there is something better or equal being widely used im happy to depricate/merge/help.

**Comment by guilhem** [comment]
Nice :)
This guy also want to speak about it: https://github.com/Fewbytes/sysctl-cookbook/pull/4

We can follow this discussion on this pull-request.
