### ISSUE TITLE
Quotes in sysctl.erb Template File

### ISSUE THREAD

**Issue by jwestboston** [spheromak/sysctl-cookbook#6]
Hi spheromak,

The file templates/default/sysctl.erb surrounds the sysctl value with double quotes.  Sysctl settings need to be set without quotes (at least on Debian) within sysctl.conf and related files.

Would it be possible to remove the quotes surrounding resource.value?

Thanks.

**Comment by spheromak** [comment]
yeap this is something that needs to get fixed.

**Comment by spheromak** [comment]
should be fixed in master, and also released v2.0.1 of jn_sysctl to community site.
