### ISSUE TITLE
Doc mismatch with attributes blows away /etc/sysctl.conf

### ISSUE THREAD

**Issue by jf647** [spheromak/sysctl-cookbook#7]
The docs say to define node['sysctl']['sysctl_file'].

The code uses the attribute node['sysctl']['config_file']

If you use this cookbook on a non-debian system and try to override the destination per the docs, you blow away your default sysctl.conf.

For platform specificity, RHEL 6.2 and up support /etc/sysctl.d (thought the directory isn't created by default):

https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/6.2_Technical_Notes/index.html#initscripts

**Comment by spheromak** [comment]
Thanks for the report.

**Comment by spheromak** [comment]
fixed in the latest commit c6acf3bb9445a1e8f653f8e98f55cec18f7e902d
